// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqCv60gcTJN9oBiBfkP-GwxELENgPQk1c',
    appId: '1:914352196749:web:b318006e2d4f7aadf866c4',
    messagingSenderId: '914352196749',
    projectId: 'renting-wala-27d06',
    authDomain: 'renting-wala-27d06.firebaseapp.com',
    databaseURL: 'https://renting-wala-27d06-default-rtdb.firebaseio.com',
    storageBucket: 'renting-wala-27d06.appspot.com',
    measurementId: 'G-D30FBEGBYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQduY28OYEnsvlmPVEakcufVeH8KBDBOQ',
    appId: '1:914352196749:android:d66c443c05a7336cf866c4',
    messagingSenderId: '914352196749',
    projectId: 'renting-wala-27d06',
    databaseURL: 'https://renting-wala-27d06-default-rtdb.firebaseio.com',
    storageBucket: 'renting-wala-27d06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP32imn2GeQfLqyUsgECsiAJ5VIbx4GTc',
    appId: '1:914352196749:ios:ba0a71b7264fd935f866c4',
    messagingSenderId: '914352196749',
    projectId: 'renting-wala-27d06',
    databaseURL: 'https://renting-wala-27d06-default-rtdb.firebaseio.com',
    storageBucket: 'renting-wala-27d06.appspot.com',
    androidClientId: '914352196749-nei2cc80dhoubgp8qjdj3at434k3sbh7.apps.googleusercontent.com',
    iosClientId: '914352196749-88vvtq7k7cbj1v7qlpunhnt52ct8h65l.apps.googleusercontent.com',
    iosBundleId: 'com.dor.customeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP32imn2GeQfLqyUsgECsiAJ5VIbx4GTc',
    appId: '1:914352196749:ios:ba0a71b7264fd935f866c4',
    messagingSenderId: '914352196749',
    projectId: 'renting-wala-27d06',
    databaseURL: 'https://renting-wala-27d06-default-rtdb.firebaseio.com',
    storageBucket: 'renting-wala-27d06.appspot.com',
    androidClientId: '914352196749-nei2cc80dhoubgp8qjdj3at434k3sbh7.apps.googleusercontent.com',
    iosClientId: '914352196749-88vvtq7k7cbj1v7qlpunhnt52ct8h65l.apps.googleusercontent.com',
    iosBundleId: 'com.dor.customeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALP7IQxXoLVrI0vHnvH948YyDjnI1btW4',
    appId: '1:914352196749:web:ec85233c37768d8df866c4',
    messagingSenderId: '914352196749',
    projectId: 'renting-wala-27d06',
    authDomain: 'renting-wala-27d06.firebaseapp.com',
    databaseURL: 'https://renting-wala-27d06-default-rtdb.firebaseio.com',
    storageBucket: 'renting-wala-27d06.appspot.com',
    measurementId: 'G-FHK0YE4K10',
  );
}
